import Head from "next/head";

const Metadata = () => (
  <Head>
    <title>Scuderia NFT</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export { Metadata };
