/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IScoot__factory } from "./IScoot__factory";
export { IScuderia__factory } from "./IScuderia__factory";
export { IStakable__factory } from "./IStakable__factory";
