/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IScuderia,
  IScuderiaInterface,
} from "../../../contracts/interfaces/IScuderia";

const _abi = [
  {
    inputs: [],
    name: "IncorrectPaymentAmount",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidMintQuantity",
    type: "error",
  },
  {
    inputs: [],
    name: "SaleInactive",
    type: "error",
  },
  {
    inputs: [],
    name: "SupplyWillBeExceeded",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_quantity",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IScuderia__factory {
  static readonly abi = _abi;
  static createInterface(): IScuderiaInterface {
    return new utils.Interface(_abi) as IScuderiaInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IScuderia {
    return new Contract(address, _abi, signerOrProvider) as IScuderia;
  }
}
