/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IScoot } from "./IScoot";
export type { IScuderia } from "./IScuderia";
export type { IStakable } from "./IStakable";
