import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Heading } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Scuderia Racing NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading>Scuderia </Heading>
        <Heading>🏎️</Heading>
      </main>
    </div>
  );
};

export default Home;
