/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/ferrari.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ferrari-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.F1_79_ferrari001_1.geometry} material={materials['Rightupperarm1Mtl.001']} />
        <mesh geometry={nodes.F1_79_ferrari001_2.geometry} material={materials['Righthand1Mtl.001']} />
        <mesh geometry={nodes.F1_79_ferrari001_3.geometry} material={materials['Aero1Mtl.001']} />
        <mesh geometry={nodes.F1_79_ferrari001_4.geometry} material={materials['Aero2Mtl.001']} />
        <mesh geometry={nodes.F1_79_ferrari001_5.geometry} material={materials['Part1Mtl.001']} />
        <mesh geometry={nodes.F1_79_ferrari001_6.geometry} material={materials['Meshesmcledgears0011Mtl.001']} />
        <mesh geometry={nodes.F1_79_ferrari001_7.geometry} material={materials['Led1Mtl.001']} />
        <mesh geometry={nodes.F1_79_ferrari001_8.geometry} material={materials['Cover1Mtl.001']} />
        <mesh geometry={nodes.F1_79_ferrari001_9.geometry} material={materials['Meshesmesh101Mtl.001']} />
        <mesh geometry={nodes.F1_79_ferrari001_10.geometry} material={materials['Livery1Mtl.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/ferrari-transformed.glb')
