/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721Stakable } from "./ERC721Stakable";
export type { Scoot } from "./Scoot";
export type { Scuderia } from "./Scuderia";
